spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cuit_paimai?serverTimezone=GMT%2B8&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: sunshixiong
            client-secret: 123456
  thymeleaf:
    cache: false
    encoding: UTF-8
    prefix: classpath:/resources/
    suffix: .html
  servlet:
    multipart:
      max-file-size: 20Mb
      max-request-size: 100Mb
server:
  port: 8081
#配置登录是返回json还是重定向
cuit:
  security:
    brower:
      loginPage: /login_in #/login//login_in
      loginTpye: JSON #REDIRECT/JSON
